### ISSUE TITLE
Not Loading anything

### ISSUE THREAD

**Issue by runcreeper** [Akuukis/sepraisal#39]
### Summary
Tried to load up this awesome tool, but when I search for any ship or collection I just get a red ERROR. RETRY?
Tried with both the latest firefox with adblock off and with microsoft Edge with nothing on it.

### Steps to Reproduce actual behavior

1. Go to https://spaceengineerspraisal.net/browse?collection=ISL+-+Utility+Ships
2. Click on Search
3. See Error Retry?

### Your Device (please complete the following information):
- OS: Win 10
- Browser Firefox, Edge
- Version Firefox 79, Edge 44.19041.423.0

### Additional context
Thankyou for having developed this awesome tool. XD

**Comment by Akuukis** [comment]
@runcreeper 

Yes, the Browse tab had awful uptime last 7 days - https://uptime.spaceengineerspraisal.net/ . Since yesterday it's finally back to normal.

The cause: Sparks of Future support was added (https://github.com/Akuukis/sepraisal/pull/37), which triggered the re-praisal of all 130'000+ blueprints. The little server (that was given by arma.lv community) can deal with daily inflow of new blueprints (<1000), but had a really hard time to congest this spike to the point of crashing, freezing, etc. I've been restarting it 20+ times over these days, as well patched some hacks to help the server to get over it. Even if server didn't crash it wouldn't do the work near-instantly anyways, and so all the not-yet-repraised blueprints would be missing from Browse, for no less than 3 days (yes it's hella of work to repraisal all of that).

What can be fixed is better informing users of what's going on. Here's a new feature request (#40) to address exactly your problem, as well the older one (#7) would go a long way to help on this too. Other related issues:
- do something about the old version - #38
- optimize the praisal process - #24 #11 #10
- find someone else that can donate a bigger server

I hope this answers your issue.
